package lufact_test

import (
	"errors"
	"math"
	"math/rand"
	"slices"
	"testing"

	"ontology/lufact"
)

const eps = 1e-9

// factorCases is the shared table: fixed cases plus random strictly
// diagonally dominant matrices (so every Doolittle pivot is nonzero) with
// negative and zero off-diagonal entries. Sizes are generated by loops.
func factorCases(t *testing.T) []struct {
	name string
	a    []float64
	n    int
} {
	t.Helper()
	cases := []struct {
		name string
		a    []float64
		n    int
	}{
		{"worked3", []float64{2, 1, 1, 4, 3, 3, 8, 7, 9}, 3},
		{"neg2", []float64{1, 0, -2, 1}, 2},
		{"neg1", []float64{-3}, 1},
		{"pos1", []float64{5}, 1},
		{"neg3", []float64{-2, -1, 0, 4, -3, 3, 8, 7, -9}, 3},
	}
	rng := rand.New(rand.NewSource(20260926))
	for _, n := range []int{2, 4, 6, 10} {
		for trial := 0; trial < 3; trial++ {
			a := make([]float64, n*n)
			for i := 0; i < n; i++ { // strictly row-dominant => nonzero pivots
				sum := 0.0
				for j := 0; j < n; j++ {
					if i == j {
						continue
					}
					v := rng.Float64()*4 - 2
					a[i*n+j] = v
					sum += math.Abs(v)
				}
				d := sum + 1 + rng.Float64()*3
				if rng.Intn(2) == 0 {
					d = -d // negative diagonal is fine while dominance holds
				}
				a[i*n+i] = d
			}
			cases = append(cases, struct {
				name string
				a    []float64
				n    int
			}{"rand", slices.Clone(a), n})
			_ = trial
		}
	}
	return cases
}

// TestFactorReconstructA pins invariant 1: L*U reproduces A elementwise.
func TestFactorReconstructA(t *testing.T) {
	for _, c := range factorCases(t) {
		t.Run(c.name, func(t *testing.T) {
			L, U, err := lufact.Factor(c.a, c.n)
			if err != nil {
				t.Fatalf("Factor: %v", err)
			}
			for i := 0; i < c.n; i++ {
				for j := 0; j < c.n; j++ {
					s := 0.0
					for k := 0; k < c.n; k++ {
						s += L[i*c.n+k] * U[k*c.n+j]
					}
					if math.Abs(s-c.a[i*c.n+j]) > eps {
						t.Fatalf("(%d,%d) L*U=%v want %v", i, j, s, c.a[i*c.n+j])
					}
				}
			}
		})
	}
}

// TestFactorUnitTriangular pins invariant 2: L has unit diagonal and zero
// entries above it; U has zero entries below its diagonal.
func TestFactorUnitTriangular(t *testing.T) {
	for _, c := range factorCases(t) {
		t.Run(c.name, func(t *testing.T) {
			L, U, err := lufact.Factor(c.a, c.n)
			if err != nil {
				t.Fatalf("Factor: %v", err)
			}
			for i := 0; i < c.n; i++ {
				if L[i*c.n+i] != 1 {
					t.Fatalf("L[%d][%d]=%v, want 1", i, i, L[i*c.n+i])
				}
				for j := 0; j < c.n; j++ {
					if j > i && L[i*c.n+j] != 0 {
						t.Fatalf("L above diagonal L[%d][%d]=%v", i, j, L[i*c.n+j])
					}
					if j < i && U[i*c.n+j] != 0 {
						t.Fatalf("U below diagonal U[%d][%d]=%v", i, j, U[i*c.n+j])
					}
				}
			}
		})
	}
}

// TestFactorErrors is table-driven over the three lufact sentinels, which
// must be distinct. Errors return nil L/U and never mutate the input.
func TestFactorErrors(t *testing.T) {
	cases := []struct {
		name string
		a    []float64
		n    int
		want error
	}{
		{"empty-nil", nil, 0, lufact.ErrEmpty},
		{"empty-neg", []float64{1}, -1, lufact.ErrEmpty},
		{"dimension", []float64{1, 2, 3}, 2, lufact.ErrDimension},
		{"zero-pivot-first", []float64{0, 1, 1, 0}, 2, lufact.ErrZeroPivot},
		{"zero-pivot-later", []float64{1, 2, 3, 2, 4, 5, 7, 8, 9}, 3, lufact.ErrZeroPivot},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			saved := slices.Clone(c.a)
			L, U, err := lufact.Factor(c.a, c.n)
			if !errors.Is(err, c.want) {
				t.Fatalf("err=%v want %v", err, c.want)
			}
			if L != nil || U != nil {
				t.Fatalf("L/U must be nil on error, got %v %v", L, U)
			}
			if !slices.Equal(c.a, saved) {
				t.Fatalf("input mutated: %v -> %v", saved, c.a)
			}
		})
	}
	if errors.Is(lufact.ErrEmpty, lufact.ErrDimension) || errors.Is(lufact.ErrDimension, lufact.ErrZeroPivot) {
		t.Fatal("sentinel errors must be distinct")
	}
}
