package sch

import (
	"fmt"
	"testing"
)

// TestReferencedCheckIsConstant builds m children spread over m parents and
// checks the P.del "has references?" probe never scans the child table: the
// unexported scan counter must stay at a size-independent constant (0), both
// for a referenced parent (delete rejected) and an unreferenced one (delete
// accepted). It also pins reference-count accuracy (invariant 3).
func TestReferencedCheckIsConstant(t *testing.T) {
	// Sizes are generated by looping over the required tiers.
	for _, m := range []int{100, 500, 1000, 2500, 5000, 10000} {
		s := NewState()
		for i := 0; i < m; i++ {
			pk := fmt.Sprintf("p%d", i)
			s.AddParent(pk)
			s.AddChild(fmt.Sprintf("c%d", i), pk)
		}

		// Referenced parent: decision must come from the count, not a scan.
		exists, refs := s.ProbeParentDelete("p0")
		if !exists || refs != 1 {
			t.Fatalf("m=%d: referenced probe = (%v,%d), want (true,1)", m, exists, refs)
		}
		const limit = 0 // constant independent of m
		if s.lastDelScanned > limit {
			t.Fatalf("m=%d: referenced probe scanned %d children, want <=%d", m, s.lastDelScanned, limit)
		}

		// Unreferenced parent: successful delete path is also scan-free.
		s.AddParent("lonely")
		if ex, r := s.ProbeParentDelete("lonely"); !ex || r != 0 {
			t.Fatalf("m=%d: unreferenced probe = (%v,%d), want (true,0)", m, ex, r)
		}
		if s.lastDelScanned > limit {
			t.Fatalf("m=%d: unreferenced probe scanned %d, want <=%d", m, s.lastDelScanned, limit)
		}
		s.RemoveParent("lonely")

		// Reference counts equal the per-parent child group sizes, here all 1.
		for i := 0; i < m; i++ {
			if got := s.RefCountOf(fmt.Sprintf("p%d", i)); got != 1 {
				t.Fatalf("m=%d: RefCountOf(p%d)=%d, want 1", m, i, got)
			}
		}
		if got := s.RefCountOf("p0"); got != 1 {
			t.Fatalf("m=%d: count before remove = %d", m, got)
		}
		s.RemoveChild("c0")
		if got := s.RefCountOf("p0"); got != 0 {
			t.Fatalf("m=%d: count after removing sole child = %d, want 0", m, got)
		}
	}
}

// TestViewsSortedAndCopied pins Parents() ordering and that returned
// snapshots are copies safe for callers to mutate.
func TestViewsSortedAndCopied(t *testing.T) {
	s := NewState()
	for _, p := range []string{"p3", "p1", "p2"} {
		s.AddParent(p)
	}
	got := s.Parents()
	want := []string{"p1", "p2", "p3"}
	if len(got) != len(want) {
		t.Fatalf("parents = %v, want %v", got, want)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Fatalf("parents = %v, want sorted %v", got, want)
		}
	}
	got[0] = "mutated"
	if s.HasParent("mutated") || !s.HasParent("p1") {
		t.Fatal("Parents() must return an independent copy")
	}
}
