package wfq

import (
	"math/rand"
	"testing"
)

// TestProbeCountConstant: with m flows across orders of magnitude, each
// holding one head packet of pairwise-distinct finish, one Dequeue must
// inspect a number of flows bounded by an m-independent small constant —
// the heap root, not an O(m) table scan. White-box: it reads the unexported
// probes field directly; no exported method ever returns that number.
func TestProbeCountConstant(t *testing.T) {
	cases := []struct{ m int }{{100}, {500}, {1000}, {5000}, {10000}}
	for _, tc := range cases {
		weights := make([]int, tc.m)
		for i := range weights {
			weights[i] = 1
		}
		s, err := New(weights)
		if err != nil {
			t.Fatalf("m=%d: New: %v", tc.m, err)
		}
		for f := 0; f < tc.m; f++ { // distinct size -> distinct finish while V=0
			if err := s.Submit(f, tc.m-f); err != nil {
				t.Fatalf("m=%d: Submit: %v", tc.m, err)
			}
		}
		flow, err := s.Dequeue()
		if err != nil {
			t.Fatalf("m=%d: Dequeue: %v", tc.m, err)
		}
		if flow != tc.m-1 { // smallest finish 1 sits on the last flow
			t.Errorf("m=%d: got flow %d, want %d", tc.m, flow, tc.m-1)
		}
		if s.probes != 1 {
			t.Errorf("m=%d: inspected %d flows, want exactly 1 (heap root)", tc.m, s.probes)
		}
	}
}

// TestFinishMonotone pins invariant 2: each flow's F strictly increases on
// Submit, queued finish times are strictly ascending, F is the tail finish
// while non-empty, and Dequeue never moves F. Random streams generated by
// loop; checks run against the internal counters.
func TestFinishMonotone(t *testing.T) {
	cases := []struct{ weights []int }{
		{[]int{1}}, {[]int{2, 1}}, {[]int{1, 2, 4}}, {[]int{3, 5, 2, 7}},
	}
	for ci, tc := range cases {
		rng := rand.New(rand.NewSource(int64(ci) + 1))
		s, _ := New(tc.weights)
		n := len(tc.weights)
		lastF := make([]int, n)
		live := 0
		for i := 0; i < 1000; i++ {
			if live == 0 || rng.Intn(2) == 0 {
				f, sz := rng.Intn(n), rng.Intn(9)+1
				if err := s.Submit(f, sz); err != nil {
					t.Fatalf("case %d: Submit: %v", ci, err)
				}
				if s.FlowFinish(f) <= lastF[f] { // inc >= 1 -> strict rise
					t.Errorf("case %d: F %d not above previous %d", ci, s.FlowFinish(f), lastF[f])
				}
				lastF[f] = s.FlowFinish(f)
				q := s.FlowQueue(f)
				for j := 1; j < len(q); j++ {
					if q[j] <= q[j-1] {
						t.Errorf("case %d flow %d: queue finishes not ascending: %v", ci, f, q)
					}
				}
				live++
			} else {
				f, err := s.Dequeue()
				if err != nil {
					t.Fatalf("case %d: Dequeue: %v", ci, err)
				}
				if s.FlowFinish(f) != lastF[f] {
					t.Errorf("case %d flow %d: Dequeue moved F to %d, want %d",
						ci, f, s.FlowFinish(f), lastF[f])
				}
				live--
			}
		}
	}
}

// TestEightStepTrace pins the NOTES.md derivation for weights=[2,1]: after
// each of the eight ops, (F0,F1,V) and the dequeued flow (-1 = Submit).
func TestEightStepTrace(t *testing.T) {
	s, _ := New([]int{2, 1})
	type row struct{ f0, f1, v, res int }
	got := []row{}
	note := func(res int) { got = append(got, row{s.FlowFinish(0), s.FlowFinish(1), s.VirtualTime(), res}) }
	if err := s.Submit(0, 2); err != nil {
		t.Fatal(err)
	}
	note(-1)
	if err := s.Submit(1, 1); err != nil {
		t.Fatal(err)
	}
	note(-1)
	d1, _ := s.Dequeue()
	note(d1)
	d2, _ := s.Dequeue()
	note(d2)
	if err := s.Submit(1, 2); err != nil {
		t.Fatal(err)
	}
	note(-1)
	d3, _ := s.Dequeue()
	note(d3)
	if err := s.Submit(0, 2); err != nil { // F0 = max(1,3)+1 = 4
		t.Fatal(err)
	}
	note(-1)
	d4, _ := s.Dequeue()
	note(d4)
	want := []row{
		{1, 0, 0, -1}, {1, 1, 0, -1}, {1, 1, 1, 0}, {1, 1, 1, 1},
		{1, 3, 1, -1}, {1, 3, 3, 1}, {4, 3, 3, -1}, {4, 3, 4, 0},
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("step %d: got %+v, want %+v", i+1, got[i], want[i])
		}
	}
}
