package deadlock

import (
	"container/heap"
	"strings"
)

// Probe is an edge-chasing message. Initiator is the transaction that
// started the probe when it began waiting; Path is the sequence of
// transactions the probe has visited, Path[0] == Initiator, and
// Path[len-1] is the transaction the probe is being delivered to.
type Probe struct {
	Initiator string
	Path      []string
}

// message is a probe plus its deterministic delivery metadata.
type message struct {
	probe   Probe
	arrival int64
	seq     int64
}

// msgHeap is a priority queue ordered by (arrival, seq) so delivery order
// is deterministic even when injected delays reorder messages.
type msgHeap []message

func (h msgHeap) Len() int { return len(h) }
func (h msgHeap) Less(i, j int) bool {
	if h[i].arrival != h[j].arrival {
		return h[i].arrival < h[j].arrival
	}
	return h[i].seq < h[j].seq
}
func (h msgHeap) Swap(i, j int) { h[i], h[j] = h[j], h[i] }
func (h *msgHeap) Push(x any)   { *h = append(*h, x.(message)) }
func (h *msgHeap) Pop() any {
	old := *h
	n := len(old)
	m := old[n-1]
	*h = old[:n-1]
	return m
}

// DeliverOne delivers the next in-flight probe, if any. It reports whether
// a message was delivered.
func (c *Cluster) DeliverOne() bool {
	c.mu.Lock()
	defer c.mu.Unlock()
	if len(c.pending) == 0 {
		return false
	}
	m := heap.Pop(&c.pending).(message)
	c.deliverLocked(m.probe)
	return true
}

// DeliverAll delivers messages until the network is empty, including
// messages generated by the deliveries themselves.
func (c *Cluster) DeliverAll() {
	for c.DeliverOne() {
	}
}

// sendLocked injects a probe into the network with a deterministic
// pseudo-random delay drawn from the cluster seed. Delays reorder messages
// relative to send order; the (arrival, seq) heap keeps the resulting
// delivery order deterministic for replay.
func (c *Cluster) sendLocked(p Probe) {
	delay := 1 + c.rng.Int63n(c.maxDelay)
	c.seq++
	m := message{probe: p, arrival: c.seq + delay, seq: c.seq}
	heap.Push(&c.pending, m)
	c.logf("[SEND] init=%s path=%s arrival=%d", p.Initiator, joinPath(p.Path), m.arrival)
}

// deliverLocked processes one probe at the site where its target
// transaction is currently blocked.
//
// Drop rules, in order:
//  1. The edge the probe just traversed no longer exists (the wait it
//     travelled along has been resolved) — drop.
//  2. The target is no longer waiting anywhere — drop.
//  3. The target already appears in the path and is not the initiator
//     (a cycle that does not include the initiator) — drop; this bounds
//     path length and guarantees termination.
//
// If the target is the initiator, every edge along the path is re-checked
// against the current wait-for graph; only if all of them still exist is a
// deadlock declared. Otherwise the probe is forwarded along every wait-for
// edge of the target.
func (c *Cluster) deliverLocked(p Probe) {
	cur := p.Path[len(p.Path)-1]
	prev := p.Path[len(p.Path)-2]
	path := joinPath(p.Path)

	if !c.edgeExistsLocked(prev, cur) {
		c.logf("[DROP] init=%s path=%s reason=edge %s->%s no longer exists", p.Initiator, path, prev, cur)
		return
	}
	site, ok := c.waitingSite[cur]
	if !ok {
		c.logf("[DROP] init=%s path=%s reason=%s is no longer waiting", p.Initiator, path, cur)
		return
	}

	if cur == p.Initiator {
		c.confirmLocked(p)
		return
	}
	for _, t := range p.Path[:len(p.Path)-1] {
		if t == cur {
			c.logf("[DROP] init=%s path=%s reason=cycle without initiator at %s", p.Initiator, path, cur)
			return
		}
	}

	targets := sortedKeys(c.sites[site].waits[cur])
	c.logf("[FORWARD] init=%s at=%s next=%v", p.Initiator, cur, targets)
	for _, next := range targets {
		newPath := make([]string, len(p.Path)+1)
		copy(newPath, p.Path)
		newPath[len(p.Path)] = next
		c.sendLocked(Probe{Initiator: p.Initiator, Path: newPath})
	}
}

// confirmLocked handles a probe that has returned to its initiator: the
// deadlock is real only if every traversed edge still exists right now.
// The victim is the transaction on the cycle with the largest start
// timestamp.
func (c *Cluster) confirmLocked(p Probe) {
	path := joinPath(p.Path)
	for i := 0; i+1 < len(p.Path); i++ {
		if !c.edgeExistsLocked(p.Path[i], p.Path[i+1]) {
			c.logf("[DROP] init=%s path=%s reason=edge %s->%s vanished before confirmation",
				p.Initiator, path, p.Path[i], p.Path[i+1])
			return
		}
	}
	cycle := p.Path[:len(p.Path)-1]
	victim := cycle[0]
	for _, id := range cycle[1:] {
		if c.txns[id].StartTS > c.txns[victim].StartTS {
			victim = id
		}
	}
	c.logf("[DEADLOCK] cycle=%s all %d edges verified present; victim=%s (startTS=%d, max on cycle)",
		path, len(cycle), victim, c.txns[victim].StartTS)
	c.abortLocked(victim)
}

func joinPath(path []string) string {
	return strings.Join(path, "->")
}
