package omap

import (
	"errors"
	"fmt"
	"testing"
)

func TestApplyValidation(t *testing.T) {
	cases := []struct {
		name string
		op   Op
		want error
	}{
		{"empty-outer", Op{Kind: Put, Outer: "", Inner: "i", Value: 1, TS: 1, Rep: "R"}, ErrEmptyOuterKey},
		{"empty-inner", Op{Kind: Put, Outer: "o", Inner: "", Value: 1, TS: 1, Rep: "R"}, ErrEmptyInnerKey},
		{"zero-ts", Op{Kind: Put, Outer: "o", Inner: "i", Value: 1, TS: 0, Rep: "R"}, ErrNonPositiveTS},
		{"negative-ts-del", Op{Kind: DelOuter, Outer: "o", TS: -1}, ErrNonPositiveTS},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := New()
			if err := m.Apply(Op{Kind: Put, Outer: "keep", Inner: "i", Value: 9, TS: 1, Rep: "R"}); err != nil {
				t.Fatal(err)
			}
			before := m.View()
			if err := m.Apply(tc.op); !errors.Is(err, tc.want) {
				t.Fatalf("err=%v want %v", err, tc.want)
			}
			if got := m.View(); fmt.Sprint(got) != fmt.Sprint(before) {
				t.Fatalf("state changed: %v", got)
			}
			if m.checked != 0 {
				t.Fatalf("rejected op inspected %d stored outer keys, want 0", m.checked)
			}
			if err := m.Apply(Op{Kind: Put, Outer: "ok", Inner: "i", Value: 2, TS: 2, Rep: "R"}); err != nil {
				t.Fatalf("unusable after rejection: %v", err)
			}
		})
	}
	if ErrEmptyOuterKey == ErrEmptyInnerKey || ErrEmptyInnerKey == ErrNonPositiveTS || ErrEmptyOuterKey == ErrNonPositiveTS {
		t.Fatal("sentinel errors must be pairwise distinct")
	}
}

// TestOuterKeyLookupIsConstantTime is the complexity proof: after m outer
// keys exist, one Apply to a known key inspects a constant number of outer
// keys regardless of m, because the outer map is located by hash rather
// than scanned. The counter is read directly (white box, same package); no
// exported method exposes its numeric value.
func TestOuterKeyLookupIsConstantTime(t *testing.T) {
	// m-independent small constant: one hash bucket.
	const bound = 1
	// Table-driven scale档位 generated by a loop.
	for _, m := range []int{100, 1000, 10000} {
		t.Run(fmt.Sprintf("m=%d", m), func(t *testing.T) {
			om := New()
			for j := 0; j < m; j++ {
				op := Op{Kind: Put, Outer: fmt.Sprintf("outer%05d", j), Inner: "i",
					Value: j, TS: int64(j + 1), Rep: "R"}
				if err := om.Apply(op); err != nil {
					t.Fatal(err)
				}
			}
			// Apply to one known existing outer key.
			if err := om.Apply(Op{Kind: Put, Outer: "outer00000", Inner: "i2",
				Value: 1, TS: int64(m + 1), Rep: "R"}); err != nil {
				t.Fatal(err)
			}
			if om.checked > bound {
				t.Fatalf("m=%d: inspected %d outer keys, bound %d (linear scan?)", m, om.checked, bound)
			}
			if om.checked != 1 {
				t.Fatalf("m=%d: checked=%d want exactly 1 hash lookup", m, om.checked)
			}
			// Same bound for a brand-new outer key.
			if err := om.Apply(Op{Kind: DelOuter, Outer: "brand-new", TS: int64(m + 2)}); err != nil {
				t.Fatal(err)
			}
			if om.checked > bound {
				t.Fatalf("m=%d: new key inspected %d, bound %d", m, om.checked, bound)
			}
		})
	}
}

func TestOMapMergeView(t *testing.T) {
	cases := []struct {
		name  string
		build func(a, b *OMap)
		want  map[string]map[string]int
	}{
		{"lww-union", func(a, b *OMap) {
			_ = a.Apply(Op{Kind: Put, Outer: "o", Inner: "k", Value: 1, TS: 5, Rep: "A"})
			_ = b.Apply(Op{Kind: Put, Outer: "o", Inner: "k", Value: 9, TS: 2, Rep: "B"})
			a.Merge(b)
		}, map[string]map[string]int{"o": {"k": 1}}},
		{"tomb-wins", func(a, b *OMap) {
			_ = a.Apply(Op{Kind: DelOuter, Outer: "o", TS: 9})
			_ = b.Apply(Op{Kind: Put, Outer: "o", Inner: "k", Value: 1, TS: 4, Rep: "B"})
			a.Merge(b)
		}, map[string]map[string]int{}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			a, b := New(), New()
			tc.build(a, b)
			if got := a.View(); fmt.Sprint(got) != fmt.Sprint(tc.want) {
				t.Fatalf("got %v want %v", got, tc.want)
			}
		})
	}
}
