package qr

import (
	"errors"
	"math"
	"math/rand"
	"sync"
	"testing"
)

const eps = 1e-9

func randMat(seed int64, n int) []float64 {
	r := rand.New(rand.NewSource(seed))
	a := make([]float64, n*n)
	for i := range a {
		a[i] = r.Float64()*4 - 2
	}
	return a
}

// sizes x seeds, generated by loop over a table.
var cases = []struct {
	seed int64
	n    int
}{{1, 1}, {2, 2}, {3, 3}, {4, 5}, {5, 9}, {6, 17}, {7, 33}} // checkQR pins invariants 1+2: Q*R == a, Q^T Q == I, R strictly upper.
func checkQR(t *testing.T, Q, R, a []float64, n int) {
	t.Helper()
	for i := 0; i < n; i++ {
		for j := 0; j < n; j++ {
			var qr, qq float64
			for k := 0; k < n; k++ {
				qr += Q[i*n+k] * R[k*n+j]
				qq += Q[k*n+i] * Q[k*n+j]
			}
			if math.Abs(qr-a[i*n+j]) > eps {
				t.Fatalf("n=%d (%d,%d): Q*R=%v want %v", n, i, j, qr, a[i*n+j])
			}
			want := 0.0
			if i == j {
				want = 1
			}
			if math.Abs(qq-want) > eps {
				t.Fatalf("n=%d: Q^TQ[%d][%d]=%v want %v", n, i, j, qq, want)
			}
			if i > j && R[i*n+j] != 0 {
				t.Fatalf("n=%d: R[%d][%d]=%v not zero", n, i, j, R[i*n+j])
			}
		}
	}
}

func TestReconstruction(t *testing.T) {
	for _, c := range cases {
		a := randMat(c.seed, c.n)
		src := append([]float64(nil), a...)
		Q, R, err := Factor(a, c.n)
		if err != nil {
			t.Fatalf("n=%d: %v", c.n, err)
		}
		checkQR(t, Q, R, a, c.n)
		for i := range a { // input is read-only
			if a[i] != src[i] {
				t.Fatalf("n=%d: input mutated at %d", c.n, i)
			}
		}
	}
}

func TestOrthogonalAndUpper(t *testing.T) {
	for _, c := range cases {
		Q, R, err := Factor(randMat(c.seed, c.n), c.n)
		if err != nil {
			t.Fatalf("n=%d: %v", c.n, err)
		}
		checkQR(t, Q, R, randMat(c.seed, c.n), c.n)
	}
}

func TestRejectionLeavesState(t *testing.T) {
	bads := []struct {
		a    []float64
		n    int
		want error
	}{
		{[]float64{1, 2, 3}, 2, ErrDimMismatch},
		{nil, 0, ErrEmptyMatrix},
		{[]float64{0, 1, 0, 1}, 2, ErrZeroTail},
	}
	for _, b := range bads {
		before := reflectorCount.Load()
		if _, _, err := Factor(b.a, b.n); !errors.Is(err, b.want) {
			t.Fatalf("want %v, got %v", b.want, err)
		}
		if reflectorCount.Load() != before {
			t.Fatal("counter moved on a rejected call")
		}
	}
	if _, _, err := Factor(randMat(9, 4), 4); err != nil {
		t.Fatalf("unusable after rejections: %v", err)
	}
}

func TestTriangularZeroCount(t *testing.T) {
	for _, n := range []int{100, 1000, 10000} {
		a := make([]float64, n*n)
		for i := 0; i < n; i++ {
			for j := i; j < n; j++ {
				a[i*n+j] = float64(i+j) + 1
			}
		}
		before := reflectorCount.Load()
		if _, _, err := Factor(a, n); err != nil {
			t.Fatalf("n=%d: %v", n, err)
		}
		if got := reflectorCount.Load() - before; got != 0 {
			t.Fatalf("n=%d: built %d reflectors on triangular input", n, got)
		}
	}
}

func TestConcurrentIdentical(t *testing.T) {
	a := randMat(42, 24)
	Q0, R0, err := Factor(a, 24)
	if err != nil {
		t.Fatal(err)
	}
	const g = 32
	qs, rs := make([][]float64, g), make([][]float64, g)
	start := make(chan struct{})
	var wg sync.WaitGroup
	for i := 0; i < g; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			<-start
			qs[i], rs[i], _ = Factor(a, 24)
		}(i)
	}
	close(start)
	wg.Wait()
	for i := 0; i < g; i++ {
		for j := range Q0 {
			if math.Float64bits(qs[i][j]) != math.Float64bits(Q0[j]) ||
				math.Float64bits(rs[i][j]) != math.Float64bits(R0[j]) {
				t.Fatalf("goroutine %d differs at element %d", i, j)
			}
		}
	}
}
