package agg

import (
	"math"
	"testing"

	"ontology/delta"
)

func ev(v int64, op delta.Op) delta.Event { return delta.Event{Val: v, Op: op} }

func TestSixStepTable(t *testing.T) {
	evs := []delta.Event{ev(5, delta.Insert), ev(2, delta.Insert), ev(9, delta.Insert),
		ev(9, delta.Retract), ev(2, delta.Insert), ev(2, delta.Retract)}
	type w struct {
		cnt, sum, mn, mx int64
		ok               bool
	}
	got := []w{
		{1, 5, 5, 5, true}, {2, 7, 2, 5, true}, {3, 16, 2, 9, true},
		{2, 7, 2, 5, true}, {3, 9, 2, 5, true}, {2, 7, 2, 5, true},
	}
	g := NewGroup()
	for i, e := range evs {
		if err := g.Apply(e); err != nil {
			t.Fatalf("step %d: %v", i+1, err)
		}
		cnt, sum, mn, mx, mok, xok := g.Value()
		p := got[i]
		if cnt != p.cnt || sum != p.sum || mn != p.mn || mx != p.mx || mok != p.ok || xok != p.ok {
			t.Fatalf("step %d = (%d,%d,%d,%d,%v,%v) want %+v", i+1, cnt, sum, mn, mx, mok, xok, p)
		}
	}
}

func TestRetractIsInverse(t *testing.T) {
	// Seed multisets cover negatives, zero and duplicates; insert then retract
	// v must restore every aggregate to its exact prior value.
	cases := []struct {
		seed []int64
		v    int64
	}{
		{nil, 5}, {[]int64{5, -3, 5, 9}, 5}, {[]int64{0, 0}, 0},
		{[]int64{-7, -7, 2}, -7},
		{[]int64{math.MaxInt64 - 1}, 1}, {[]int64{math.MinInt64 + 1}, -1},
	}
	for _, tc := range cases {
		g := NewGroup()
		for _, v := range tc.seed {
			if err := g.Apply(ev(v, delta.Insert)); err != nil {
				t.Fatal(err)
			}
		}
		snap := func() [6]any {
			c, s, mn, mx, a, b := g.Value()
			return [6]any{c, s, mn, mx, a, b}
		}
		before := snap()
		if err := g.Apply(ev(tc.v, delta.Insert)); err != nil {
			t.Fatal(err)
		}
		if err := g.Apply(ev(tc.v, delta.Retract)); err != nil {
			t.Fatal(err)
		}
		if after := snap(); after != before {
			t.Fatalf("seed %v v %d: %v != before %v", tc.seed, tc.v, after, before)
		}
	}
}

func TestEmptyGroupSemantics(t *testing.T) {
	g := NewGroup()
	if cnt, sum, _, _, mok, xok := g.Value(); cnt != 0 || sum != 0 || mok || xok {
		t.Fatalf("fresh group cnt=%d sum=%d ok=%v,%v", cnt, sum, mok, xok)
	}
	for _, e := range []delta.Event{ev(0, delta.Insert), ev(0, delta.Insert),
		ev(0, delta.Retract), ev(0, delta.Retract)} {
		if err := g.Apply(e); err != nil {
			t.Fatal(err)
		}
	}
	if cnt, _, _, _, mok, xok := g.Value(); cnt != 0 || mok || xok {
		t.Fatalf("drained group cnt=%d ok=%v,%v (want absent, not 0)", cnt, mok, xok)
	}
	if err := g.Apply(ev(0, delta.Insert)); err != nil {
		t.Fatal(err)
	}
	if _, _, _, _, mok, xok := g.Value(); !mok || !xok {
		t.Fatal("a single live zero must report MIN/MAX present")
	}
}

func TestApplyErrorsAtomic(t *testing.T) {
	cases := []struct {
		name string
		run  func(*Group) error
		want error
	}{
		{"retract missing empty", func(g *Group) error { return g.Apply(ev(4, delta.Retract)) }, delta.ErrRetractMissing},
		{"retract after drain", func(g *Group) error {
			_ = g.Apply(ev(4, delta.Insert))
			_ = g.Apply(ev(4, delta.Retract))
			return g.Apply(ev(4, delta.Retract))
		}, delta.ErrRetractMissing},
		{"sum overflow positive", func(g *Group) error {
			_ = g.Apply(ev(math.MaxInt64, delta.Insert))
			return g.Apply(ev(1, delta.Insert))
		}, ErrSumOverflow},
		{"sum overflow negative", func(g *Group) error {
			_ = g.Apply(ev(math.MinInt64, delta.Insert))
			return g.Apply(ev(-1, delta.Insert))
		}, ErrSumOverflow},
		{"retract overflows too", func(g *Group) error { // sum=MaxInt64, retract -5 -> out of range
			for _, v := range []int64{-5, math.MaxInt64, 5} {
				_ = g.Apply(ev(v, delta.Insert))
			}
			return g.Apply(ev(-5, delta.Retract))
		}, ErrSumOverflow},
	}
	for _, tc := range cases {
		g := NewGroup()
		if err := tc.run(g); err != tc.want {
			t.Fatalf("%s: %v want %v", tc.name, err, tc.want)
		}
	}
}

// TestSublinearVisit seeds m values then applies a change and asserts stored
// nodes entered stay within a small constant times log2(m); a linear rescan
// would scale with m. Sizes are generated by a loop, not enumerated.
func TestSublinearVisit(t *testing.T) {
	for _, m := range []int{100, 1000, 10000} {
		g := NewGroup()
		for i := 0; i < m; i++ {
			if err := g.Apply(ev(int64(i), delta.Insert)); err != nil {
				t.Fatal(err)
			}
		}
		limit := 8.0 * math.Log2(float64(m))
		for _, e := range []delta.Event{ev(-1, delta.Insert), ev(int64(m/2), delta.Retract)} {
			if err := g.Apply(e); err != nil {
				t.Fatal(err)
			}
			if float64(g.visited) > limit {
				t.Fatalf("m=%d %v visited %d > %.1f", m, e.Op, g.visited, limit)
			}
		}
	}
}
