package doc

import (
	"testing"

	"ontology/rga"
)

// TestInsertLookupProbe builds an m-element chain and inserts one more
// element after a known anchor. The unexported probe must stay at a
// constant independent of m: predecessor location is a hash lookup, not a
// scan over all elements. Sizes are generated by a loop.
func TestInsertLookupProbe(t *testing.T) {
	sizes := []int{100, 500, 1000, 5000, 10000}
	base := -1
	for _, m := range sizes {
		t.Run("", func(t *testing.T) {
			d := New()
			var prev rga.ID
			for i := 1; i <= m; i++ {
				id := rga.ID{Lamport: i, Replica: "A"}
				if err := d.Insert(prev, id, 'a'); err != nil {
					t.Fatalf("m=%d seed insert: %v", m, err)
				}
				prev = id
			}
			anchor := rga.ID{Lamport: 1, Replica: "A"}
			err := d.Insert(anchor, rga.ID{Lamport: m + 1, Replica: "Z"}, 'z')
			if err != nil {
				t.Fatalf("m=%d insert after anchor: %v", m, err)
			}
			got := d.probe()
			const bound = 1 // root=0 examined, existing prev=1 hash hit
			if got > bound {
				t.Fatalf("m=%d probe=%d, want <= %d (linear scan?)", m, got, bound)
			}
			if base == -1 {
				base = got
			} else if got != base {
				t.Fatalf("m=%d probe=%d, want same constant %d for all m", m, got, base)
			}
		})
	}
}

func TestProbeIsConstant(t *testing.T) {
	if !ProbeIsConstant() {
		t.Fatal("ProbeIsConstant returned false")
	}
}
