// Package framing implements a streaming HTTP/1.x request framing decision
// engine for a reverse-proxy ingress.
//
// See DESIGN.md for the full specification, rationale and verification method.
package framing

// EventKind identifies the kind of event emitted by a Parser.
type EventKind int

const (
	EventHeaderComplete EventKind = iota
	EventBody
	EventRequestEnd
	EventReject
)

// BodyMode is the framing mode decided for a request.
type BodyMode int

const (
	BodyNone BodyMode = iota
	BodyFixedLength
	BodyChunked
)

// RejectReason is a mutually distinguishable rejection category.
type RejectReason int

const (
	RejectNone RejectReason = iota
	RejectHeaderTooLarge
	RejectZeroByte
	RejectBareLF
	RejectSyntax
	RejectLengthAndTransferEncoding
	RejectContentLengthInvalid
	RejectLengthTooLarge
	RejectTransferEncodingUnsupported
	RejectChunkFormatInvalid
	RejectTrailerInvalid
)

// String returns a stable human-readable name for the rejection reason.
func (r RejectReason) String() string {
	if int(r) < 0 || int(r) >= len(reasonNames) {
		return "invalid"
	}
	return reasonNames[r]
}

var reasonNames = [...]string{
	"none",
	"header_too_large",
	"zero_byte",
	"bare_lf",
	"syntax",
	"length_and_transfer_encoding",
	"content_length_invalid",
	"length_too_large",
	"transfer_encoding_unsupported",
	"chunk_format_invalid",
	"trailer_invalid",
}

// Event is a single output event of the framing decision engine.
type Event struct {
	Kind   EventKind
	Method string
	Target string
	// Version is "1.0" or "1.1" for EventHeaderComplete.
	Version string
	// Mode is the decided body framing for EventHeaderComplete.
	Mode BodyMode
	// N is the number of body bytes for EventBody.
	N int
	// Reason is the rejection category for EventReject.
	Reason RejectReason
}

// Config configures a Parser. Both limits are in bytes.
type Config struct {
	MaxHeaderBytes int
	MaxBodyBytes   uint64
}

// DefaultConfig returns conservative default limits.
func DefaultConfig() Config {
	return Config{MaxHeaderBytes: 64 * 1024, MaxBodyBytes: 1 << 40}
}

// parsePhase is the state of the per-request byte stream state machine.
type parsePhase int

const (
	phaseHeaders parsePhase = iota
	phaseFixed
	phaseChunkSize
	phaseChunkExt
	phaseChunkCR
	phaseChunkData
	phaseChunkDataCR
	phaseChunkDataLF
	phaseTrailerLine
	phaseTrailerCR
	phaseTrailerEndCR
)

// Parser decides framing for a single connection.
//
// All mutable state is bounded: the only byte buffers (hdrBuf and lineBuf)
// are bounded by MaxHeaderBytes, and every counter is a machine integer.
// Memory therefore does not grow with message-body length or with the number
// of requests seen on the connection.
//
// A Parser is safe for concurrent use by multiple callers: concurrent Feed
// calls are serialized and the combined event sequence is equivalent to some
// serial ordering of the supplied chunks.
type Parser struct {
	mu     chan struct{}
	cfg    Config
	closed bool

	phase parsePhase

	// Header accumulation for the current request.
	hdrBuf    []byte
	hdrLen    int
	lastWasCR bool

	// Decoded result of the current request's header block.
	method    string
	target    string
	version   string
	mode      BodyMode
	fixedLeft uint64
	bodySeen  uint64

	// Chunked body parsing.
	lineBuf   []byte
	chunkLeft uint64

	// Body bytes accumulated since the last flush point.
	pendingBody uint64
}

// NewParser creates a connection-scoped parser. Zero-valued limits in cfg
// fall back to DefaultConfig values.
func NewParser(cfg Config) *Parser {
	def := DefaultConfig()
	if cfg.MaxHeaderBytes <= 0 {
		cfg.MaxHeaderBytes = def.MaxHeaderBytes
	}
	if cfg.MaxBodyBytes == 0 {
		cfg.MaxBodyBytes = def.MaxBodyBytes
	}
	p := &Parser{mu: make(chan struct{}, 1), cfg: cfg, phase: phaseHeaders}
	p.mu <- struct{}{}
	p.hdrBuf = make([]byte, 0, 256)
	p.lineBuf = make([]byte, 0, 64)
	return p
}

// Feed delivers one byte chunk in arrival order and returns the events
// generated by this chunk. Events for a connection must be concatenated in
// call order to obtain the full event sequence. The returned slice is valid
// until the next Feed/FeedInto call on this parser.
func (p *Parser) Feed(chunk []byte) []Event {
	return p.FeedInto(make([]Event, 0, 4), chunk)
}

// FeedInto is Feed but appends events into the caller-provided slice, which
// allows hot-path use with zero heap allocations.
func (p *Parser) FeedInto(events []Event, chunk []byte) []Event {
	<-p.mu
	defer func() { p.mu <- struct{}{} }()
	if p.closed {
		return events
	}
	for i := 0; i < len(chunk); i++ {
		b := chunk[i]
		if p.phase == phaseHeaders {
			events = p.feedHeaderByte(events, b)
		} else {
			events = p.feedBodyByte(events, b)
		}
		if p.closed {
			break
		}
	}
	// Emit body bytes accumulated up to this chunk boundary. Adjacent body
	// events merge, so callers can compare results independently of chunking.
	if !p.closed {
		events = p.flushBody(events)
	}
	return events
}

// Closed reports whether the connection has been rejected.
func (p *Parser) Closed() bool {
	<-p.mu
	defer func() { p.mu <- struct{}{} }()
	return p.closed
}

func (p *Parser) reject(events []Event, reason RejectReason) []Event {
	p.closed = true
	return append(events, Event{Kind: EventReject, Reason: reason})
}

// flushBody emits pending body bytes, merging with an immediately preceding
// body event.
func (p *Parser) flushBody(events []Event) []Event {
	if p.pendingBody == 0 {
		return events
	}
	n := p.pendingBody
	p.pendingBody = 0
	if len(events) > 0 && events[len(events)-1].Kind == EventBody {
		events[len(events)-1].N += int(n)
		return events
	}
	return append(events, Event{Kind: EventBody, N: int(n)})
}
