package window

import "bytes"

// Window is a fixed-capacity ring. Distance 1 is the most recent byte.
type Window struct {
	buf   []byte
	start int
	len   int
}

func New(capacity int) *Window {
	if capacity <= 0 {
		panic("window: capacity must be positive")
	}
	return &Window{buf: make([]byte, capacity)}
}

func (w *Window) Cap() int { return len(w.buf) }
func (w *Window) Len() int { return w.len }

func (w *Window) Reset() {
	w.start = 0
	w.len = 0
}

func (w *Window) Add(b byte) {
	if w.len < len(w.buf) {
		w.buf[(w.start+w.len)%len(w.buf)] = b
		w.len++
		return
	}
	w.buf[w.start] = b
	w.start = (w.start + 1) % len(w.buf)
}

func (w *Window) At(distance int) byte {
	if distance < 1 || distance > w.len {
		panic("window: distance out of range")
	}
	return w.buf[(w.start+w.len-distance)%len(w.buf)]
}

// CopyFrom appends length bytes generated by distance. Distance must refer to
// an existing byte. Overlapping references expand forward.
func (w *Window) CopyFrom(dst []byte, distance, length int) []byte {
	if distance < 1 || distance > w.len || length < 0 {
		panic("window: invalid copy reference")
	}
	first := length
	if first > distance {
		first = distance
	}
	base := len(dst)
	for i := 0; i < first; i++ {
		dst = append(dst, w.At(distance-i))
	}
	if remaining := length - first; remaining > 0 {
		pattern := dst[len(dst)-distance:]
		times := (remaining + distance - 1) / distance
		dst = append(dst, bytes.Repeat(pattern, times)...)
		dst = dst[:base+length]
	}
	return dst
}
