package topk

import (
	"math/bits"
	"testing"

	"ontology/ord"
)

// TestOrderAndHeapPrimitives pins the deterministic total order and both
// heap directions of the ord primitive (ord itself has no test file).
func TestOrderAndHeapPrimitives(t *testing.T) {
	less := []struct {
		a, b ord.Elem
		want bool
	}{
		{ord.Elem{ID: "a", Score: 2}, ord.Elem{ID: "b", Score: 1}, true},  // higher score first
		{ord.Elem{ID: "b", Score: 1}, ord.Elem{ID: "a", Score: 2}, false}, // symmetric
		{ord.Elem{ID: "a", Score: 1}, ord.Elem{ID: "b", Score: 1}, true},  // tie -> smaller id
		{ord.Elem{ID: "b", Score: 1}, ord.Elem{ID: "a", Score: 1}, false},
		{ord.Elem{ID: "a", Score: 1}, ord.Elem{ID: "a", Score: 1}, false}, // irreflexive
	}
	for i, c := range less {
		if got := ord.Less(c.a, c.b); got != c.want {
			t.Fatalf("case %d: Less=%v want %v", i, got, c.want)
		}
	}
	// Best-first heap pops in ranking order; worst-first heap reverses it.
	best := ord.NewHeap[entry](rankLess, nil)
	worst := ord.NewHeap[entry](func(a, b entry) bool { return rankLess(b, a) }, nil)
	for _, e := range []ord.Elem{{ID: "c", Score: 1}, {ID: "a", Score: 3}, {ID: "b", Score: 3}} {
		best.Push(entry{e: e})
		worst.Push(entry{e: e})
	}
	wantBest := []string{"a", "b", "c"}
	for i, id := range wantBest {
		if got := best.Pop().e.ID; got != id {
			t.Fatalf("best pop %d = %s want %s", i, got, id)
		}
	}
	for i, id := range []string{"c", "b", "a"} {
		if got := worst.Pop().e.ID; got != id {
			t.Fatalf("worst pop %d = %s want %s", i, got, id)
		}
	}
}

// TestBelowThresholdOpsAreLogN fills n elements, then inserts one new id
// strictly below the threshold and reads the unexported counter directly:
// heap work for that single add must be O(log n), never O(n). Scales are
// generated by a loop; the counter value enters no exported signature.
func TestBelowThresholdOpsAreLogN(t *testing.T) {
	for _, n := range []int{100, 500, 1000, 5000, 10000} {
		m := New(10, n+10)
		for i := 0; i < n; i++ {
			m.Add(ord.Elem{ID: idFor(i), Score: int64(i)})
		}
		m.Add(ord.Elem{ID: "below", Score: -1})
		bound := int64(8 * (1 + bits.Len(uint(n))))
		if m.ops >= int64(n) {
			t.Fatalf("n=%d: ops=%d is not strictly below n", n, m.ops)
		}
		if m.ops > bound {
			t.Fatalf("n=%d: ops=%d exceeds O(log n) bound %d", n, m.ops, bound)
		}
		if m.Count() != n+1 {
			t.Fatalf("n=%d: count=%d want %d", n, m.Count(), n+1)
		}
	}
}

// TestBackfillAndUpsertAtTopkLevel exercises lazy deletion: an upsert that
// moves an id across the threshold and a removal that forces backfill must
// leave exactly the naive best-k in top.
func TestBackfillAndUpsertAtTopkLevel(t *testing.T) {
	m := New(2, 10)
	for _, e := range []ord.Elem{{ID: "a", Score: 1}, {ID: "b", Score: 2}, {ID: "c", Score: 3}, {ID: "d", Score: 4}} {
		m.Add(e)
	}
	if got := idsOf(m.Tops()); !eqStrings(got, []string{"d", "c"}) {
		t.Fatalf("tops=%v want [d c]", got)
	}
	m.Add(ord.Elem{ID: "a", Score: 100}) // below-threshold id jumps to the top
	if got := idsOf(m.Tops()); !eqStrings(got, []string{"a", "d"}) {
		t.Fatalf("after upsert tops=%v want [a d]", got)
	}
	m.Remove("a") // threshold removal: next best (c) must backfill
	if got := idsOf(m.Tops()); !eqStrings(got, []string{"d", "c"}) {
		t.Fatalf("after remove tops=%v want [d c]", got)
	}
	m.Remove("b") // b is below the threshold: top must be unchanged
	if got := idsOf(m.Tops()); !eqStrings(got, []string{"d", "c"}) {
		t.Fatalf("below-threshold remove changed tops=%v", got)
	}
}

func idFor(i int) string {
	return "x" + string(rune('a'+i%26)) + itoa(i/26)
}
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	return string(b)
}
func idsOf(es []ord.Elem) []string {
	out := make([]string, len(es))
	for i, e := range es {
		out[i] = e.ID
	}
	return out
}
func eqStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}
