package adapt

import "testing"

// TestSettlementScanConstant pins the O(1) per-event accounting: after a
// window of m events settles, the non-exported counter of rescanned events
// must stay below a small constant independent of m. Sizes are generated by a
// loop over several orders of magnitude.
func TestSettlementScanConstant(t *testing.T) {
	const bound int64 = 1 // m-independent small constant; implementation uses 0
	for _, m := range []int64{100, 1000, 10000} {
		w, err := New(0, m, 1, m, 1, 0)
		if err != nil {
			t.Fatalf("m=%d New: %v", m, err)
		}
		for i := int64(0); i < m; i++ {
			w.Feed(m - i)
		}
		w.mu.RLock()
		scanned, n := w.lastSettlementScanned, w.n
		w.mu.RUnlock()
		if n != 0 {
			t.Errorf("m=%d: window did not settle (n=%d)", m, n)
		}
		if scanned > bound {
			t.Errorf("m=%d: settlement rescanned %d events, want <= %d (linear scan?)", m, scanned, bound)
		}
	}
}

// TestSettlementScannedStaysZeroAcrossWindows makes sure the counter records a
// direct counter read on every settlement, including delay-moving ones.
func TestSettlementScannedStaysZeroAcrossWindows(t *testing.T) {
	cases := []struct {
		name             string
		minD, maxD, step int64
		events           []int64
	}{
		{"raise", 0, 10, 2, []int64{100, 1, 2}},
		{"lower", 2, 10, 2, []int64{10, 11, 12}},
		{"neutral", 2, 10, 2, []int64{10, 7, 12}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			w, err := New(c.minD, c.maxD, c.step, 3, 2, 0)
			if err != nil {
				t.Fatal(err)
			}
			for _, ts := range c.events {
				w.Feed(ts)
			}
			w.mu.RLock()
			scanned := w.lastSettlementScanned
			w.mu.RUnlock()
			if scanned != 0 {
				t.Errorf("scanned=%d, want 0", scanned)
			}
		})
	}
}
