package api_test

import (
	"errors"
	"math/rand"
	"reflect"
	"sync"
	"testing"

	"ontology/api"
)

// ref is the mutex-guarded naive reference: one hazard map and a linear
// per-node scan over a plain retired slice.
type ref struct {
	mu sync.Mutex
	h  map[int]int
	r  []int
}

func newRef() *ref { return &ref{h: map[int]int{}} }
func (m *ref) set(id, n int) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if n <= 0 {
		return api.ErrInvalidNode
	}
	if _, ok := m.h[id]; ok {
		return api.ErrAlreadyHeld
	}
	m.h[id] = n
	return nil
}

func (m *ref) clr(id int) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if _, ok := m.h[id]; !ok {
		return api.ErrNotProtected
	}
	delete(m.h, id)
	return nil
}

func (m *ref) ret(n int) error {
	m.mu.Lock()
	defer m.mu.Unlock()
	if n <= 0 {
		return api.ErrInvalidNode
	}
	for _, x := range m.r {
		if x == n {
			return api.ErrAlreadyRetired
		}
	}
	m.r = append(m.r, n)
	return nil
}

func (m *ref) rec() []int {
	m.mu.Lock()
	defer m.mu.Unlock()
	held := map[int]bool{}
	for _, v := range m.h {
		held[v] = true
	}
	var freed, kept []int
	for _, x := range m.r {
		if held[x] {
			kept = append(kept, x)
		} else {
			freed = append(freed, x)
		}
	}
	m.r = kept
	return freed
}

// TestNaiveEquivalence pins invariant 1: identical random op sequences give
// the same errors and per-Reclaim freed sets as the mutex reference.
func TestNaiveEquivalence(t *testing.T) {
	rng, real, refm := rand.New(rand.NewSource(7)), api.New(), newRef()
	for i := 0; i < 3000; i++ {
		id, n := 1+rng.Intn(5), 1+rng.Intn(9)
		if rng.Intn(7) == 0 {
			n = 0
		}
		var e1, e2 error
		var f1, f2 []int
		switch rng.Intn(4) {
		case 0:
			e1, e2 = real.Protect(id, n), refm.set(id, n)
		case 1:
			e1, e2 = real.Unprotect(id), refm.clr(id)
		case 2:
			e1, e2 = real.Retire(n), refm.ret(n)
		case 3:
			f1, f2 = real.Reclaim(), refm.rec()
		}
		if !errors.Is(e1, e2) || !reflect.DeepEqual(f1, f2) {
			t.Fatalf("step %d: %v/%v vs %v/%v", i, e1, f1, e2, f2)
		}
	}
}

// TestReclaimSafety pins invariant 2: every freed node is pointed at by no
// hazard slot at the verdict (the snapshot taken right before Reclaim).
func TestReclaimSafety(t *testing.T) {
	rng, r := rand.New(rand.NewSource(3)), api.New()
	for i := 0; i < 2000; i++ {
		id, n := 1+rng.Intn(5), 1+rng.Intn(9)
		switch rng.Intn(3) {
		case 0:
			r.Protect(id, n)
		case 1:
			r.Unprotect(id)
		case 2:
			r.Retire(n)
		}
		s := r.Snapshot()
		for _, f := range r.Reclaim() {
			for _, h := range s.Hazards {
				if h == f {
					t.Fatalf("step %d freed protected node %d", i, f)
				}
			}
		}
	}
}

// TestEventualReclaim pins invariant 3: retired nodes held by hazards free as
// soon as protection is dropped; sizes are generated by a loop.
func TestEventualReclaim(t *testing.T) {
	for _, m := range []int{1, 8, 64} {
		r := api.New()
		for i := 1; i <= m; i++ {
			r.Protect(i, i)
			r.Retire(i)
		}
		if len(r.Reclaim()) != 0 {
			t.Fatal("a held node was reclaimed")
		}
		for i := 1; i <= m; i++ {
			r.Unprotect(i)
		}
		if len(r.Reclaim()) != m {
			t.Fatal("a retired node was not eventually reclaimed")
		}
	}
}
