package api_test

import (
	"errors"
	"reflect"
	"sync"
	"sync/atomic"
	"testing"

	"ontology/api"
	"ontology/hazard"
)

// TestErrorsLeaveNoTrace pins invariant 4: four distinct sentinel errors and
// zero state change per rejection. Cases are generated from a table.
func TestErrorsLeaveNoTrace(t *testing.T) {
	cases := []struct {
		pre, op, id, n int
		want           error
	}{
		{0, 0, 1, 0, api.ErrInvalidNode},    // Protect with node 0
		{0, 2, 0, 0, api.ErrInvalidNode},    // Retire node 0
		{1, 2, 0, 7, api.ErrAlreadyRetired}, // Retire 7 twice
		{0, 1, 3, 0, api.ErrNotProtected},   // Unprotect empty slot
		{2, 0, 2, 6, api.ErrAlreadyHeld},    // Protect over held slot
	}
	seen := map[error]bool{}
	for _, c := range cases {
		r := api.New()
		if c.pre == 1 {
			r.Retire(7)
		}
		if c.pre == 2 {
			r.Protect(2, 5)
		}
		before := r.Snapshot()
		var err error
		switch c.op {
		case 0:
			err = r.Protect(c.id, c.n)
		case 1:
			err = r.Unprotect(c.id)
		case 2:
			err = r.Retire(c.n)
		}
		if !errors.Is(err, c.want) {
			t.Fatalf("case %+v: %v", c, err)
		}
		after := r.Snapshot()
		if !reflect.DeepEqual(before.Hazards, after.Hazards) ||
			!reflect.DeepEqual(before.Retired, after.Retired) {
			t.Fatalf("case %+v left a trace", c)
		}
		seen[c.want] = true
	}
	if len(seen) != 4 {
		t.Fatalf("want 4 distinct sentinels, got %d", len(seen))
	}
}

// TestConstantLookup pins section 4: judging one retired node inspects a slot
// count independent of m; sizes are generated by a loop and only pass/fail
// crosses the package boundary, never the counter value.
func TestConstantLookup(t *testing.T) {
	for _, m := range []int{100, 1000, 10000} {
		if err := hazard.New().CheckConstantLookup(m); err != nil {
			t.Fatalf("m=%d: %v", m, err)
		}
	}
}

// TestConcurrentReclaimSafety pins invariant 2 under concurrency. Workers
// protect a unique node, hold it across a Reclaim driven over channels (no
// sleeps), then unprotect. Atomic flags assert no freed node was still held
// and each node is reclaimed exactly once.
func TestConcurrentReclaimSafety(t *testing.T) {
	const nw, rounds = 8, 25
	tot := nw * rounds
	r := api.New()
	held := make([]atomic.Int64, tot+1)
	cnt := make([]atomic.Int32, tot+1)
	ret, done, ack := make(chan int), make(chan int), make(chan struct{})
	var wg sync.WaitGroup
	for w := 1; w <= nw; w++ {
		wg.Add(1)
		go func(w int) {
			defer wg.Done()
			for k := 0; k < rounds; k++ {
				id := k*nw + w
				if err := r.Protect(w, id); err != nil {
					t.Error(err)
					return
				}
				r.Snapshot() // concurrent Snapshot for -race coverage
				held[id].Store(1)
				ret <- id
				<-ack // node stays protected across this Reclaim
				// Clear the oracle BEFORE releasing the hazard pointer, so
				// held==1 always implies the slot really protects id.
				held[id].Store(0)
				if err := r.Unprotect(w); err != nil {
					t.Error(err)
					return
				}
				done <- id
			}
		}(w)
	}
	check := func(fs []int) {
		for _, f := range fs {
			if held[f].Load() != 0 {
				t.Errorf("node %d reclaimed while protected", f)
			}
			cnt[f].Add(1)
		}
	}
	for rN, dN := tot, tot; rN > 0 || dN > 0; {
		select {
		case id := <-ret:
			if err := r.Retire(id); err != nil {
				t.Fatal(err)
			}
			check(r.Reclaim())
			ack <- struct{}{}
			rN--
		case <-done:
			check(r.Reclaim())
			dN--
		}
	}
	wg.Wait()
	for i := 1; i <= tot; i++ {
		if cnt[i].Load() != 1 {
			t.Fatalf("node %d reclaimed %d times", i, cnt[i].Load())
		}
	}
	if s := r.Snapshot(); len(s.Hazards) != 0 || len(s.Retired) != 0 {
		t.Fatalf("leftover state %+v", s)
	}
}

// TestSelfCheck exercises the exported built-in verification.
func TestSelfCheck(t *testing.T) {
	if err := api.New().SelfCheck(); err != nil {
		t.Fatal(err)
	}
}
